### ISSUE TITLE
SC parameters only showing 1 value

### ISSUE THREAD

**Issue by pbarrow** [modexp/daqana#6]
Not sure if this is common, or just me, but looking in the SC parameters in the processed root file, all the values are the same over the time period of the data. The Modudaq is showing normal fluctuations in the parameters, but they dont seem to be ending up in the processed root file.

**Comment by cassie-fletcher** [comment]
Hi Peter,

Out of curiosity, what is the initial time as stated in the XML file?

Cheers,

Cassie

**Comment by pbarrow** [comment]
Hi Cassie,

The Initial time in the XML file is 0.

Cheers,

Peter

**Comment by cassie-fletcher** [comment]
Hi Peter,

In that case, I bet that the initial time is the problem, since the
timestamps are used to do the matching.  I think in an older version of
ModuDAQ, I missed a wire from the initial NIST timestamp to the XML file,
which causes the timestamp to always be zero.  I'll make sure it's fixed in
the current version of ModuDAQ, but you can check if this wire is connected
for yourself -- let me know if you need help.

In the mean time, to test daqana, you should be able to take the first
timestamp of the slow tree, and put it into the XML file for initial time,
reprocess, and all your data should match up.

Cheers,

Cassie

**Comment by cassie-fletcher** [comment]
To amend the second paragraph slightly, you can edit the XML file to have
the right timestamp, or just wire the NIST time to the XML file.  :)

**Comment by adambrown1** [comment]
I think this issue is now resolved, or at least it is not a problem for Zurich. Unless anyone objects I will close this issue.
