### ISSUE TITLE
Analysis is a dependency of daqana

### ISSUE THREAD

**Issue by sanderbreur** [modexp/daqana#9]
Right now we have made the analysis repository a dependency of daqana. Ether we should put that information in the installation instructions (on the wiki page) or move the analysis repository into the daqana repository for clarity.

**Comment by adambrown1** [comment]
Since we are unlikely to merge these repositories for the time being and there is another argument which says they should be separate to make it easy to have them stored in different locations, I have modified the installation instructions (http://www.physics.purdue.edu/darkmatters/doku.php?id=modulation:daq:daqana&#install) and propose to close this issue. Note that fixing the related issue #10 also makes this less annoying.
